parameters:
    mediata.field_type.ezpage.class: MediataCom\MediataEzpageFieldtypeBundle\Core\FieldType\Page\Type
    
services:
    ibexa.field_type.ezpage:
        class: "%mediata.field_type.ezpage.class%"
        parent: ezpublish.fieldType
        arguments: ["@ibexa.field_type.ezpage.pageService", "@ibexa.field_type.ezpage.hashConverter"]
        tags:
            - {name: ezplatform.field_type, alias: ezpage}

    ibexa.page_field_type.not_indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        tags:
            - { name: ezplatform.field_type.indexable, alias: ezpage }