services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    MediataCom\MediataEzpageFieldtypeLib\FieldType\Mapper\PageFormMapper:
        arguments:
            $pageService: '@ibexa.field_type.ezpage.pageService'
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: ezpage }
