services:
    MediataCom\MediataEzpageFieldtypeBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\PageConverter:
        class: MediataCom\MediataEzpageFieldtypeBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\PageConverter
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: ezpage }