services:
    MediataCom\MediataEzpageFieldtypeBundle\Core\MVC\Symfony\View\Builder\BlockViewBuilder:
        class: MediataCom\MediataEzpageFieldtypeBundle\Core\MVC\Symfony\View\Builder\BlockViewBuilder
        arguments:
            - "@ibexa.field_type.ezpage.pageService"
            - '@ezpublish.view.configurator'
            - '@ezpublish.view.view_parameters.injector.dispatcher'
                
    MediataCom\MediataEzpageFieldtypeBundle\View\Manager:
        class: MediataCom\MediataEzpageFieldtypeBundle\View\Manager
        arguments:
            - "@twig"
            - "@event_dispatcher"
            - '@ezpublish.api.repository'
            - '@ezpublish.config.resolver'
            - '%ezpublish.content_view.viewbase_layout%'
            - '@ezpublish.view.configurator'
            - "@?logger"